#!/bin/bash
NAME=webapps
{
    #Remove old box
    rm output/$NAME.box
    #Remove old generated content
    rm -rf output-autogenerated_1 
    #Stops any vm running
    vagrant destroy -f
    # Update configuration file
    packer hcl2_upgrade -with-annotations $NAME.json
    #Remove old install for vagrant
    vagrant box remove eseo/$NAME
    #Build
    packer build $NAME.json.pkr.hcl
    #Add box to vagrant local boxes
    vagrant box add output/$NAME.box --name eseo/$NAME
    #Start box for testing
    vagrant up

} || {
    echo "[!!!] - An error occurred during the build"
}