#!/bin/bash

{
    #Remove old box
    rm output/docker-root.box
    #Remove old generated content
    rm -rf output-autogenerated_1 
    #Stops any vm running
    vagrant destroy -f
    # Update configuration file
    packer hcl2_upgrade -with-annotations docker-root.json
    #Remove old install for vagrant
    vagrant box remove eseo/docker-root
    #Build
    packer build docker-root.json.pkr.hcl
    #Add box to vagrant local boxes
    vagrant box add output/docker-root.box --name eseo/docker-root
    #Start box for testing
    vagrant up

} || {
    echo "[!!!] - An error occurred during the build"
}