#!/bin/bash

{
    #Remove old box
    rm output/bruteforce.box
    #Remove old generated content
    rm -rf output-autogenerated_1 
    #Stops any vm running
    vagrant destroy -f
    # Update configuration file
    packer hcl2_upgrade -with-annotations bruteforce.json
    #Remove old install for vagrant
    vagrant box remove eseo/bruteforce
    #Build
    packer build bruteforce.json.pkr.hcl
    #Add box to vagrant local boxes
    vagrant box add output/bruteforce.box --name eseo/bruteforce
    #Start box for testing
    vagrant up

} || {
    echo "[!!!] - An error occurred during the build"
}