# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "cpus" {
  type    = string
  default = "1"
}

variable "disk_size" {
  type    = string
  default = "5120"
}

variable "iso_checksum" {
  type    = string
  default = "1f2ecf3eec6013c49224445c469069b269dae47efb8e161bc6334c6611c3a1ec"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha256"
}

variable "iso_download_url" {
  type    = string
  default = "https://mirror.archlinux.ikoula.com/iso/2021.10.01/archlinux-2022.01.01-x86_64.iso"
}

variable "iso_local_url" {
  type    = string
  default = "data/archlinux-2022.01.01-x86_64.iso"
}

variable "memory" {
  type    = string
  default = "6144"
}

variable "root_password" {
  type    = string
  default = "vagrant"
}

variable "ssh_password" {
  type    = string
  default = "vagrant"
}

variable "ssh_username" {
  type    = string
  default = "vagrant"
}

variable "vm_name" {
  type    = string
  default = "archlinux"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "virtualbox-iso" "autogenerated_1" {
  boot_command         = ["<enter><wait40>", "archinstall<enter><wait25>", "26<enter><wait5>", "19<enter><wait5>", "1<enter><wait5>", "<enter><wait5>", "0<enter><wait5>", "1<enter><wait5>", "<enter><wait5>", "n<enter><wait5>", "arch<enter><wait5>", "${var.ssh_password}<enter><wait5>", "${var.ssh_password}<enter><wait5>", "2<enter><wait5>", "7<enter><wait5>", "<enter><wait5>", "2<enter>wait5>", "<enter><wait5>", "<enter><wait5>", "<enter><wait5>", "2<enter><wait5>", "0<enter><wait5>", "Europe/Paris<enter><wait5>", "<enter><wait5>", "<enter><wait250>", "<enter><wait5>", "useradd -m vagrant<enter><wait5>", "yes ${var.ssh_password} | passwd vagrant<enter><wait5>", "exit<enter><wait5>", "reboot<enter><wait20>", "root<enter><wait5>", "${var.ssh_password}<enter><wait5>", "pacman -Sy -q --noconfirm<enter><wait5>", "pacman -S  -q --noconfirm openssh<enter><wait10>", "echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config<enter><wait5>", "echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config<enter><wait5>", "sed -i 's;AuthorizedKeysFile     .ssh/authorized_keys;AuthorizedKeysFile /home/%u/.ssh/authorized_keys;' /etc/ssh/sshd_config<enter><wait5>", "systemctl start sshd<enter><wait5>", "systemctl enable sshd<enter><wait5>", "reboot<enter><wait15>"]
  boot_wait            = "10s"
  communicator         = "ssh"
  disk_size            = "${var.disk_size}"
  format               = "ova"
  guest_additions_mode = "disable"
  guest_os_type        = "Linux26_64"
  headless             = false
  iso_checksum         = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_urls             = ["${var.iso_local_url}", "${var.iso_download_url}"]
  keep_registered      = "false"
  shutdown_command     = "/sbin/poweroff"
  ssh_password         = "${var.ssh_password}"
  ssh_timeout          = "10m"
  ssh_username         = "root"
  vboxmanage           = [["modifyvm", "{{ .Name }}", "--memory", "${var.memory}"], ["modifyvm", "{{ .Name }}", "--cpus", "${var.cpus}"], ["modifyvm", "{{ .Name }}", "--rtcuseutc", "on"], ["modifyvm", "{{ .Name }}", "--graphicscontroller", "vmsvga"], ["modifyvm", "{{ .Name }}", "--vram", "6"], ["modifyvm", "{{ .Name }}", "--vrde", "off"]]
  vm_name              = "${var.vm_name}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  description = "Build base Archlinux"

  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    scripts = ["scripts/config.sh", "scripts/srv_minecraft.sh"]
  }

  post-processor "vagrant" {
    output               = "output/archlinux.box"
    vagrantfile_template = "data/vagrantfile-archlinux.template"
  }
}
